language: python

python: "3.6"

cache: 
  - pip
  - directories:
    - ./.venv

install:
  - pip install pipenv
  - pipenv install --ignore-pipfile

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_VENV_IN_PROJECT=1

jobs:
  include:
    - stage: Deplot-Netlify-Test
      if: branch = develop
      script:
        - pipenv run invoke download
        - pipenv run invoke buildDevelop
      deploy:
        provider: pages
        repo: elc/elc.github.io
        target_branch: test
        skip_cleanup: true
        local_dir: output
        github_token: $GITHUB_TOKEN
        on:
            branch: develop
    - stage: Deploy-GitHub-Pages
      if: branch = master
      script:
        - pipenv run invoke download
        - pipenv run invoke buildProduction
      deploy:
        provider: pages
        repo: elc/elc.github.io
        target_branch: master
        skip_cleanup: true
        local_dir: output
        github_token: $GITHUB_TOKEN
        on:
            branch: master
    