os: "linux"

language: python

dist: "xenial"
python: "3.7"

cache: 
  - pip
  - directories:
    - ./.venv

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_VENV_IN_PROJECT=1
    - ENVIRONMENT=PRODUCTION
    - GITHUB_ACCESS=$GITHUB_TOKEN

install:
  - pip install pipenv
  - pipenv install --ignore-pipfile --deploy
  - npm install -g sass

script: pipenv run build

deploy:
  provider: pages
  strategy: git
  repo: elc/elc.github.io
  target_branch: master
  local_dir: output
  token: $GITHUB_TOKEN
  edge: true
  on:
      branch: source
