language: python

dist: "xenial"
python: "3.7"

cache: 
  - pip
  - directories:
    - ./.venv

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_VENV_IN_PROJECT=1
    - ENVIRONMENT=PRODUCTION

install:
  - pip install pipenv
  - pipenv install --ignore-pipfile
  - npm install -g sass

script: pipenv run build

deploy:
  provider: pages
  repo: elc/elc.github.io
  target_branch: master
  skip_cleanup: true
  local_dir: output
  github_token: $GITHUB_TOKEN
  on:
      branch: source
