language: python

sudo: false

script:
    - invoke build

deploy:
  provider: pages
  repo: elc/elc.github.io
  target_branch: master
  skip_cleanup: true
  local_dir: output
  github_token: $GITHUB_TOKEN
  on:
    branch: master
